spring:
  dependencies:
    web:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-web

    graphql:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-graphql

    thymeleaf:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-thymeleaf

    security:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-security

    jpa:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-data-jpa

    jdbc:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-data-jdbc

    mysql:
      groupId: com.mysql
      artifactId: mysql-connector-j

    h2:
      groupId: com.h2database
      artifactId: h2

    validation:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-validation

    lombok:
      groupId: org.projectlombok
      artifactId: lombok